/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAME54 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define LP_ACT_WAKEUP GPIO(GPIO_PORTA, 2)
#define LP_SGA_PG GPIO(GPIO_PORTA, 3)
#define LP_SGA_UART2_TX GPIO(GPIO_PORTA, 4)
#define LP_SGA_UART2_RX GPIO(GPIO_PORTA, 5)
#define LP_CAN1_ERR GPIO(GPIO_PORTA, 6)
#define LP_CAN1_STB GPIO(GPIO_PORTA, 7)
#define PA16 GPIO(GPIO_PORTA, 16)
#define PA17 GPIO(GPIO_PORTA, 17)
#define PA18 GPIO(GPIO_PORTA, 18)
#define LP_CAN1_TX GPIO(GPIO_PORTA, 22)
#define LP_CAN1_RX GPIO(GPIO_PORTA, 23)
#define LP_CAN0_ERR GPIO(GPIO_PORTA, 27)
#define LP_SWDCLK GPIO(GPIO_PORTA, 30)
#define LP_SWDIO GPIO(GPIO_PORTA, 31)
#define LP_CAN0_WAKEUP GPIO(GPIO_PORTB, 0)
#define LP_HPA_PG GPIO(GPIO_PORTB, 1)
#define LP_CAN1_WAKEUP GPIO(GPIO_PORTB, 2)
#define LP_HIA_PG GPIO(GPIO_PORTB, 6)
#define LP_CAN01_EN GPIO(GPIO_PORTB, 7)
#define LP_HIB_UART5_TX GPIO(GPIO_PORTB, 8)
#define LP_HIB_UART5_RX GPIO(GPIO_PORTB, 9)
#define LP_CAN0_TX GPIO(GPIO_PORTB, 12)
#define LP_CAN0_RX GPIO(GPIO_PORTB, 13)
#define LP_HIB_PG GPIO(GPIO_PORTB, 14)
#define LP_5V0_PG GPIO(GPIO_PORTB, 15)
#define LP_HIA_UART3_TX GPIO(GPIO_PORTB, 16)
#define LP_HIA_UART3_RX GPIO(GPIO_PORTB, 17)
#define LP_UART0_RX GPIO(GPIO_PORTB, 24)
#define LP_UART0_TX GPIO(GPIO_PORTB, 25)
#define LP_EXCAN_WAKEUP GPIO(GPIO_PORTC, 0)
#define LP_LIN_WAKEUP GPIO(GPIO_PORTC, 1)
#define LP_HIA_BAT_ON GPIO(GPIO_PORTC, 2)
#define LP_HIB_BAT_ON GPIO(GPIO_PORTC, 3)
#define PC04 GPIO(GPIO_PORTC, 4)
#define PC05 GPIO(GPIO_PORTC, 5)
#define LP_PWRYANK_SHDN GPIO(GPIO_PORTC, 6)
#define LP_SGA_BAT_ON GPIO(GPIO_PORTC, 10)
#define LP_CAN0_STB GPIO(GPIO_PORTC, 13)
#define LP_HPA_UART1_TX GPIO(GPIO_PORTC, 22)
#define LP_HPA_UART1_RX GPIO(GPIO_PORTC, 23)
#define LP_5V0_EN GPIO(GPIO_PORTD, 0)
#define LP_EEPROM_SDA GPIO(GPIO_PORTD, 8)
#define LP_EEPROM_SCL GPIO(GPIO_PORTD, 9)
#define PD10 GPIO(GPIO_PORTD, 10)

#endif // ATMEL_START_PINS_H_INCLUDED
